# Generated by Django 4.1.2 on 2022-11-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default='anon', max_length=120),
            preserve_default=False,
        ),
    ]
